version: '3'

services:
    oaisim:
        build:
            context: ./
            #dockerfile: ./Dockerfile
            dockerfile: ./Dockerfile_for_base
            # 環境変数を渡す（ビルド用）
            args:
                - USER=root
                - HTTP_PROXY=$HTTP_PROXY
                - http_proxy=$http_proxy
                - HTTPS_PROXY=$HTTPS_PROXY
                - https_proxy=$https_proxy
                - FTP_PROXY=$FTP_PROXY
                - ftp_proxy=$ftp_proxy
                - NO_PROXY=$NO_PROXY
                - no_proxy=$no_proxy
                - LANG=C
        
        # コンテナ名を明示的に指定する
        container_name: oaisim
        # ホスト名を明示的に指定する
        #hostname: web-server
        volumes: 
            - '/lib/modules:/lib/modules'
            - '/usr/src:/usr/src'
            - '/dev/bus/usb:/dev/bus/usb'
            - /tmp/.X11-unix:/tmp/.X11-unix
            - '../../data/oaisim:/workdir/share'

        # 環境変数を渡す（コンテナ用）
        environment:
            - USER=root
            - HTTP_PROXY=$HTTP_PROXY
            - http_proxy=$http_proxy
            - HTTPS_PROXY=$HTTPS_PROXY
            - https_proxy=$https_proxy
            - FTP_PROXY=$FTP_PROXY
            - ftp_proxy=$ftp_proxy
            - NO_PROXY=$NO_PROXY
            - no_proxy=$no_proxy
            - LANG=C
            - DISPLAY=${DISPLAY}
        tty: true
        privileged: true
        cap_add: 
            - ALL
        networks:
            oaisim-network:
                ipv4_address: 192.168.1.2

networks:
    oaisim-network:
        driver: bridge
        ipam:
            driver: default
            config:
                - subnet: 192.168.1.0/24