version: '3'

services:
    test-ubuntu-1:
        # test1イメージをビルドする
        build:
            context: ./test1
            # 環境変数を渡す（ビルド用）
            args:
                - HTTP_PROXY=$HTTP_PROXY
                - http_proxy=$http_proxy
                - HTTPS_PROXY=$HTTPS_PROXY
                - https_proxy=$https_proxy
                - FTP_PROXY=$FTP_PROXY
                - ftp_proxy=$ftp_proxy
                - NO_PROXY=$NO_PROXY
                - no_proxy=$no_proxy
        
        # コンテナ名を明示的に指定する
        container_name: test1
        # ホスト名を明示的に指定する
        #hostname: web-server

        # 環境変数を渡す（コンテナ用）
        environment:
            - HTTP_PROXY=$HTTP_PROXY
            - http_proxy=$http_proxy
            - HTTPS_PROXY=$HTTPS_PROXY
            - https_proxy=$https_proxy
            - FTP_PROXY=$FTP_PROXY
            - ftp_proxy=$ftp_proxy
            - NO_PROXY=$NO_PROXY
            - no_proxy=$no_proxy
            - LANG=$LANG

        # 終了させない
        tty: true
        networks:
            test-network:
                ipv4_address: 192.168.10.100

    test-ubuntu-2:
        build:
            context: ./test1
            args:
                - HTTP_PROXY=$HTTP_PROXY
                - http_proxy=$http_proxy
                - HTTPS_PROXY=$HTTPS_PROXY
                - https_proxy=$https_proxy
                - FTP_PROXY=$FTP_PROXY
                - ftp_proxy=$ftp_proxy
                - NO_PROXY=$NO_PROXY
                - no_proxy=$no_proxy
        container_name: test2
        #hostname: web-server
        environment:
            - HTTP_PROXY=$HTTP_PROXY
            - http_proxy=$http_proxy
            - HTTPS_PROXY=$HTTPS_PROXY
            - https_proxy=$https_proxy
            - FTP_PROXY=$FTP_PROXY
            - ftp_proxy=$ftp_proxy
            - NO_PROXY=$NO_PROXY
            - no_proxy=$no_proxy
            - LANG=$LANG
        tty: true
        networks:
            test-network:
                ipv4_address: 192.168.10.101

networks:
    test-network:
        driver: bridge
        ipam:
            driver: default
            config:
                - subnet: 192.168.10.0/24
