version: '3'

services:
    test-ubuntu-1:
        build:
            context: ./test-ubuntu
            args:
                - HTTP_PROXY=$HTTP_PROXY
                - http_proxy=$http_proxy
                - HTTPS_PROXY=$HTTPS_PROXY
                - https_proxy=$https_proxy
                - FTP_PROXY=$FTP_PROXY
                - ftp_proxy=$ftp_proxy
                - NO_PROXY=$NO_PROXY
                - no_proxy=$no_proxy
        environment:
            - HTTP_PROXY=$HTTP_PROXY
            - http_proxy=$http_proxy
            - HTTPS_PROXY=$HTTPS_PROXY
            - https_proxy=$https_proxy
            - FTP_PROXY=$FTP_PROXY
            - ftp_proxy=$ftp_proxy
            - NO_PROXY=$NO_PROXY
            - no_proxy=$no_proxy

        # 終了させない
        tty: true
        networks:
            - test-network

    test-ubuntu-2:
        build:
            context: ./test-ubuntu
            args:
                - HTTP_PROXY=$HTTP_PROXY
                - http_proxy=$http_proxy
                - HTTPS_PROXY=$HTTPS_PROXY
                - https_proxy=$https_proxy
                - FTP_PROXY=$FTP_PROXY
                - ftp_proxy=$ftp_proxy
                - NO_PROXY=$NO_PROXY
                - no_proxy=$no_proxy
        environment:
            - HTTP_PROXY=$HTTP_PROXY
            - http_proxy=$http_proxy
            - HTTPS_PROXY=$HTTPS_PROXY
            - https_proxy=$https_proxy
            - FTP_PROXY=$FTP_PROXY
            - ftp_proxy=$ftp_proxy
            - NO_PROXY=$NO_PROXY
            - no_proxy=$no_proxy
        # 終了させない
        tty: true
        networks:
            - test-network

networks:
    test-network:
        driver: bridge
        ipam:
            driver: default
            config:
                - subnet: 192.168.10.0/24
