version: '3'

services:
    srslte:
        build:
            context: ./srslte
            dockerfile: Dockerfile_imageonly
            args:
                - HTTP_PROXY=$HTTP_PROXY
                - http_proxy=$http_proxy
                - HTTPS_PROXY=$HTTPS_PROXY
                - https_proxy=$https_proxy
                - FTP_PROXY=$FTP_PROXY
                - ftp_proxy=$ftp_proxy
                - NO_PROXY=$NO_PROXY
                - no_proxy=$no_proxy
                - LANG=C
        container_name: srslte
        cap_add:
            - NET_ADMIN
            - SYS_NICE
        devices:
            - /dev/net/tun
        volumes: 
            - '../data/srslte:/workdir/share'
        environment:
            - HTTP_PROXY=$HTTP_PROXY
            - http_proxy=$http_proxy
            - HTTPS_PROXY=$HTTPS_PROXY
            - https_proxy=$https_proxy
            - FTP_PROXY=$FTP_PROXY
            - ftp_proxy=$ftp_proxy
            - NO_PROXY=$NO_PROXY
            - no_proxy=$no_proxy
            - LANG=C
        tty: true
        privileged: true
        networks:
            private-network:
                ipv4_address: 192.168.1.4

networks:
    private-network:
        driver: bridge
        ipam:
            driver: default
            config:
                - subnet: 192.168.1.0/24
