version: '3'

services:

    mnist_api:
        build:
            context: ./mnist_api
            args:
                - HTTP_PROXY=$HTTP_PROXY
                - http_proxy=$http_proxy
                - HTTPS_PROXY=$HTTPS_PROXY
                - https_proxy=$https_proxy
                - FTP_PROXY=$FTP_PROXY
                - ftp_proxy=$ftp_proxy
                - NO_PROXY=$NO_PROXY
                - no_proxy=$no_proxy
                - LANG=C
        container_name: mnist-api-server
        environment:
            - HTTP_PROXY=$HTTP_PROXY
            - http_proxy=$http_proxy
            - HTTPS_PROXY=$HTTPS_PROXY
            - https_proxy=$https_proxy
            - FTP_PROXY=$FTP_PROXY
            - ftp_proxy=$ftp_proxy
            - NO_PROXY=$NO_PROXY
            - no_proxy=$no_proxy
            - LANG=C
        expose:
            - '80'
            - '80/tcp'
        # ports:
        #     - "8080:8080"
        volumes:
            - ./mnist_api/app:/usr/src/app
        networks:
            career_net:
                ipv4_address: 192.168.30.3
            edge_net:
                ipv4_address: 192.168.32.3


    coredns-career:
        build:
            context: ./coredns-career
            args:
                - HTTP_PROXY=$HTTP_PROXY
                - http_proxy=$http_proxy
                - HTTPS_PROXY=$HTTPS_PROXY
                - https_proxy=$https_proxy
                - FTP_PROXY=$FTP_PROXY
                - ftp_proxy=$ftp_proxy
                - NO_PROXY=$NO_PROXY
                - no_proxy=$no_proxy
                - LANG=C
        container_name: coredns-career-server
        restart: on-failure
        environment:
            - HTTP_PROXY=$HTTP_PROXY
            - http_proxy=$http_proxy
            - HTTPS_PROXY=$HTTPS_PROXY
            - https_proxy=$https_proxy
            - FTP_PROXY=$FTP_PROXY
            - ftp_proxy=$ftp_proxy
            - NO_PROXY=$NO_PROXY
            - no_proxy=$no_proxy
            - LANG=C
        expose:
            - '53'
            - '53/udp'
        # ports:
        #     - '5300:53'
        #     - '5300:53/udp'
        volumes:
            - './coredns-career/conf:/etc/coredns'
        networks:
            career_net:
                ipv4_address: 192.168.30.2

    coredns-edge:
        build:
            context: ./coredns-edge
            args:
                - HTTP_PROXY=$HTTP_PROXY
                - http_proxy=$http_proxy
                - HTTPS_PROXY=$HTTPS_PROXY
                - https_proxy=$https_proxy
                - FTP_PROXY=$FTP_PROXY
                - ftp_proxy=$ftp_proxy
                - NO_PROXY=$NO_PROXY
                - no_proxy=$no_proxy
                - LANG=C
        container_name: coredns-edge-server
        restart: on-failure
        environment:
            - HTTP_PROXY=$HTTP_PROXY
            - http_proxy=$http_proxy
            - HTTPS_PROXY=$HTTPS_PROXY
            - https_proxy=$https_proxy
            - FTP_PROXY=$FTP_PROXY
            - ftp_proxy=$ftp_proxy
            - NO_PROXY=$NO_PROXY
            - no_proxy=$no_proxy
            - LANG=C
        expose:
            - '53'
            - '53/udp'
        # ports:
        #     - '5300:53'
        #     - '5300:53/udp'
        volumes:
            - './coredns-edge/conf:/etc/coredns'
        networks:
            edge_net:
                ipv4_address: 192.168.32.2
            career_net:
                ipv4_address: 192.168.30.200

networks:
    career_net:
        driver: bridge
        driver_opts:
            com.docker.network.bridge.name: br_career
        ipam:
            driver: default
            config:
                - subnet: 192.168.30.0/24
    edge_net:
        driver: bridge
        driver_opts:
            com.docker.network.bridge.name: br_edge
        ipam:
            driver: default
            config:
                - subnet: 192.168.32.0/24