version: '3'

services:
    oaisim1:
        build:
            context: ./oaisim
            dockerfile: ./oaisim/Dockerfile
            # 環境変数を渡す（ビルド用）
            args:
                - HTTP_PROXY=$HTTP_PROXY
                - http_proxy=$http_proxy
                - HTTPS_PROXY=$HTTPS_PROXY
                - https_proxy=$https_proxy
                - FTP_PROXY=$FTP_PROXY
                - ftp_proxy=$ftp_proxy
                - NO_PROXY=$NO_PROXY
                - no_proxy=$no_proxy
                - LANG=C
        
        # コンテナ名を明示的に指定する
        container_name: oaisim1
        volumes: 
            - '/lib/modules:/lib/modules'
            - '/usr/src:/usr/src'
            - '/dev/bus/usb:/dev/bus/usb'
            - /tmp/.X11-unix:/tmp/.X11-unix
            - '../data/oaisim/workdir/share:'

        # 環境変数を渡す（コンテナ用）
        environment:
            - HTTP_PROXY=$HTTP_PROXY
            - http_proxy=$http_proxy
            - HTTPS_PROXY=$HTTPS_PROXY
            - https_proxy=$https_proxy
            - FTP_PROXY=$FTP_PROXY
            - ftp_proxy=$ftp_proxy
            - NO_PROXY=$NO_PROXY
            - no_proxy=$no_proxy
            - LANG=C
            - DISPLAY=${DISPLAY}
        tty: true
        privileged: true
        cap_add: 
            - ALL
        networks:
            private-network:
                ipv4_address: 192.168.1.2

    oaisim2:
        build:
            context: ./oaisim
            dockerfile: ./oaisim/Dockerfile
            args:
                - HTTP_PROXY=$HTTP_PROXY
                - http_proxy=$http_proxy
                - HTTPS_PROXY=$HTTPS_PROXY
                - https_proxy=$https_proxy
                - FTP_PROXY=$FTP_PROXY
                - ftp_proxy=$ftp_proxy
                - NO_PROXY=$NO_PROXY
                - no_proxy=$no_proxy
                - LANG=C
        
        # コンテナ名を明示的に指定する
        container_name: oaisim2
        volumes: 
            - '/lib/modules:/lib/modules'
            - '/usr/src:/usr/src'
            - '/dev/bus/usb:/dev/bus/usb'
            - /tmp/.X11-unix:/tmp/.X11-unix
            - '../data/oaisim/workdir/share:'

        # 環境変数を渡す（コンテナ用）
        environment:
            - HTTP_PROXY=$HTTP_PROXY
            - http_proxy=$http_proxy
            - HTTPS_PROXY=$HTTPS_PROXY
            - https_proxy=$https_proxy
            - FTP_PROXY=$FTP_PROXY
            - ftp_proxy=$ftp_proxy
            - NO_PROXY=$NO_PROXY
            - no_proxy=$no_proxy
            - LANG=C
            - DISPLAY=${DISPLAY}
        tty: true
        privileged: true
        cap_add: 
            - ALL
        networks:
            private-network:
                ipv4_address: 192.168.1.3

services:
    oaisim:
        build:
            context: ./srslte
            args:
                - HTTP_PROXY=$HTTP_PROXY
                - http_proxy=$http_proxy
                - HTTPS_PROXY=$HTTPS_PROXY
                - https_proxy=$https_proxy
                - FTP_PROXY=$FTP_PROXY
                - ftp_proxy=$ftp_proxy
                - NO_PROXY=$NO_PROXY
                - no_proxy=$no_proxy
                - LANG=C
        container_name: srslte
        cap_add:
            - NET_ADMIN
            - SYS_NICE
        devices:
            - /dev/net/tun
        volumes: 
            - '../data/srslte:/workdir/share'
        environment:
            - HTTP_PROXY=$HTTP_PROXY
            - http_proxy=$http_proxy
            - HTTPS_PROXY=$HTTPS_PROXY
            - https_proxy=$https_proxy
            - FTP_PROXY=$FTP_PROXY
            - ftp_proxy=$ftp_proxy
            - NO_PROXY=$NO_PROXY
            - no_proxy=$no_proxy
            - LANG=C
        tty: true
        privileged: true
        networks:
            private-network:
                ipv4_address: 192.168.1.4

networks:
    private-network:
        driver: bridge
        ipam:
            driver: default
            config:
                - subnet: 192.168.1.0/24
