version: '3'

services:

    nginx:
        build:
            context: ./nginx
            args:
                - HTTP_PROXY=$HTTP_PROXY
                - http_proxy=$http_proxy
                - HTTPS_PROXY=$HTTPS_PROXY
                - https_proxy=$https_proxy
                - FTP_PROXY=$FTP_PROXY
                - ftp_proxy=$ftp_proxy
                - NO_PROXY=$NO_PROXY
                - no_proxy=$no_proxy
                - LANG=C
        container_name: nginx-server
        environment:
            - HTTP_PROXY=$HTTP_PROXY
            - http_proxy=$http_proxy
            - HTTPS_PROXY=$HTTPS_PROXY
            - https_proxy=$https_proxy
            - FTP_PROXY=$FTP_PROXY
            - ftp_proxy=$ftp_proxy
            - NO_PROXY=$NO_PROXY
            - no_proxy=$no_proxy
            - LANG=C
        expose:
            - '80'
            - '80/tcp'
        # ports:
        #     - "8080:8080"
        volumes:
            - ./nginx/conf:/etc/nginx/conf.d
        networks:
            career_net:
                ipv4_address: 192.168.30.3
            edge_net:
                ipv4_address: 192.168.32.3


    coredns:
        build:
            context: ./coredns
            args:
                - HTTP_PROXY=$HTTP_PROXY
                - http_proxy=$http_proxy
                - HTTPS_PROXY=$HTTPS_PROXY
                - https_proxy=$https_proxy
                - FTP_PROXY=$FTP_PROXY
                - ftp_proxy=$ftp_proxy
                - NO_PROXY=$NO_PROXY
                - no_proxy=$no_proxy
                - LANG=C
        container_name: coredns-dns-server
        restart: on-failure
        environment:
            - HTTP_PROXY=$HTTP_PROXY
            - http_proxy=$http_proxy
            - HTTPS_PROXY=$HTTPS_PROXY
            - https_proxy=$https_proxy
            - FTP_PROXY=$FTP_PROXY
            - ftp_proxy=$ftp_proxy
            - NO_PROXY=$NO_PROXY
            - no_proxy=$no_proxy
            - LANG=C
        expose:
            - '53'
            - '53/udp'
        # ports:
        #     - '5300:53'
        #     - '5300:53/udp'
        volumes:
            - './coredns/conf:/etc/coredns'
        networks:
            career_net:
                ipv4_address: 192.168.30.2
            edge_net:
                ipv4_address: 192.168.32.2

networks:
    career_net:
        driver: bridge
        driver_opts:
            com.docker.network.bridge.name: br_career
        ipam:
            driver: default
            config:
                - subnet: 192.168.30.0/24
    edge_net:
        driver: bridge
        driver_opts:
            com.docker.network.bridge.name: br_edge
        ipam:
            driver: default
            config:
                - subnet: 192.168.32.0/24