version: '3'

services:
    nginx:
        build:
            context: ./
            args:
                - HTTP_PROXY=$HTTP_PROXY
                - http_proxy=$http_proxy
                - HTTPS_PROXY=$HTTPS_PROXY
                - https_proxy=$https_proxy
                - FTP_PROXY=$FTP_PROXY
                - ftp_proxy=$ftp_proxy
                - NO_PROXY=$NO_PROXY
                - no_proxy=$no_proxy
                - LANG=C
        container_name: nginx_contents
        environment:
            - HTTP_PROXY=$HTTP_PROXY
            - http_proxy=$http_proxy
            - HTTPS_PROXY=$HTTPS_PROXY
            - https_proxy=$https_proxy
            - FTP_PROXY=$FTP_PROXY
            - ftp_proxy=$ftp_proxy
            - NO_PROXY=$NO_PROXY
            - no_proxy=$no_proxy
            - LANG=C
        ports:
            - "8080:8080"
        volumes:
            - ./conf:/etc/nginx/conf.d
            # - ./contents:/usr/share/nginx/html
