version: '3'

services:
    oaisim:
        build:
            context: ./
            # 環境変数を渡す（ビルド用）
            args:
                - HTTP_PROXY=$HTTP_PROXY
                - http_proxy=$http_proxy
                - HTTPS_PROXY=$HTTPS_PROXY
                - https_proxy=$https_proxy
                - FTP_PROXY=$FTP_PROXY
                - ftp_proxy=$ftp_proxy
                - NO_PROXY=$NO_PROXY
                - no_proxy=$no_proxy
                - LANG=$LANG
        
        # コンテナ名を明示的に指定する
        container_name: oaisim
        # ホスト名を明示的に指定する
        #hostname: web-server
        volumes: 
            - '/home/orikaito/Documents/share/:/workdir/share/'
            - '/lib/modules/:/lib/modules/:ro'
            - '/usr/src/:/usr/src/:ro'

        # 環境変数を渡す（コンテナ用）
        environment:
            - HTTP_PROXY=$HTTP_PROXY
            - http_proxy=$http_proxy
            - HTTPS_PROXY=$HTTPS_PROXY
            - https_proxy=$https_proxy
            - FTP_PROXY=$FTP_PROXY
            - ftp_proxy=$ftp_proxy
            - NO_PROXY=$NO_PROXY
            - no_proxy=$no_proxy
            - LANG=$LANG
        tty: true